export const CART_ACTION_TYPES = {
  SET_CURRENCY: "SET_CURRENCY",
  SET_CART_DROPDOWN: "SET_CART_DROPDOWN",
  UPDATE_CART_ITEMS: "UPDATE_CART_ITEMS",
  UPDATE_ORDER_ID_START: "UPDATE_ORDER_ID_START",
  UPDATE_ORDER_ID_SUCCESS: "UPDATE_ORDER_ID_SUCCESS",
  UPDATE_ORDER_ID_FAILURE: "UPDATE_ORDER_ID_FAILURE",
  CLEAR_CART: "CLEAR_CART",
};
